#! /bin/sh

sleep 1 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &
>$HOME/.log.bspfloat.txt &
# polybar &
pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/conky/Auva/start.sh &
# /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
# xfce4-power-manager &
# bash $HOME/.config/bspwm/scripts/fix-plank
xsetroot -cursor_name left_ptr &
# compositor
# picom --experimental-backends --config $HOME/.config/picom/picom.conf &
# picom &
feh --bg-fill ~/.wallpapers/tokyo.png
# ukui-window-switch &
# parcellite &
# plank &
cfw &
fcitx &
copyq &

/home/lon/.local/bin/eww daemon && /home/lon/.local/bin/eww open bar &
fullscreen &
xset r rate 300 60

bspc monitor -d 1 2 3 4 5 6
# sleep 1 && bsp-layout set grid 5

bspc config border_width 5
bspc config window_gap 10
bspc config border_radius 10

config top_padding 20
config left_padding 20
config right_padding 20

config pointer_modifier mod4
config pointer_action1 move
config pointer_action2 resize_side
config pointer_action2 resize_corner

bspc config normal_border_color \#c0caf5
bspc config active_border_color \#00ff00
bspc config focused_border_color \#F66B60

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Peek state=floating
# bspc rule -a kitty state=floating
bspc config external_rules_command "$HOME/.config/bspwm/scripts/external-rules"
bspc rule -a conky-manager2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plank manage=off border=off locked=on focus=off follow=off layer=above
bspc rule -a Rofi state=floating
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=1920x1080+0+0
bspc rule -a copyq state=floating
