apiVersion: v1
kind: Pod
metadata:
 name: __NAME__
 namespace: test
spec:
 containers:
 - name: never-exit-container
   image: __IMAGE__
   command: ["/bin/sh"]
   args: ["-c", "while true; do echo 'This pod never exits, delete it mannually'; sleep 3600; done"]
