prod-conf := "$HOME/.kube/prod.config"
test-conf := "$HOME/.kube/test.config"
dev-conf  := "$HOME/.kube/dev.config"
exec-pod *args:
	python ~/.recipes/k8s/k8s.py exec-pod {{args}}

debug-pod *args:
	python ~/.recipes/k8s/k8s.py pod-debug {{args}}

set-prod:
	rm $HOME/.kube/config && ln -s {{prod-conf}} $HOME/.kube/config

set-test:
	rm $HOME/.kube/config && ln -s {{test-conf}} $HOME/.kube/config

set-dev:
	rm $HOME/.kube/config && ln -s {{dev-conf}} $HOME/.kube/config

prod-k9s: set-prod
	k9s

test-k9s: set-test
	k9s